#!/usr/bin/env python
from misc.utility.scons_hints import *

Import("env")
Import("env_modules")

env_cbt = env_modules.Clone()

# CBT Content Studio Module Source Files
env_cbt.add_source_files(env.modules_sources, "*.cpp")
